### ISSUE TITLE
Player controller bugs

### ISSUE THREAD

**Issue by natashamyra** [natashamyra/RPG-game#2]
Problem:

Players control another player, vice versa.

Script involved:
CarUserController
![Screenshot 2021-12-20 164052 PNG](https://user-images.githubusercontent.com/89892386/146737861-58e65c36-f41d-4523-baf1-d0f7e941a76c.jpg)
PlayerController
SpawnPoint

Under branch:
Main

@scarffy

**Comment by scarffy** [comment]
@natashamyra Is there any dev branch I can have a look at? or I can just create new branch under main?

**Comment by natashamyra** [comment]
@scarffy  is it okay to do under Machine branch?

**Comment by scarffy** [comment]
😂😂 im asking you because you are the project owner
